### ISSUE TITLE
Cannot start tedis in Ubuntu 16.04

### ISSUE THREAD

**Issue by kcech** [vvondra/tedis#2]
Hello,
I tried using both node 6 and 8, letest versions, with nvm..
The command `npm run electron` fails. The debug log contains:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/kcech/.nvm/versions/node/v8.2.1/bin/node',
1 verbose cli   '/home/kcech/.nvm/versions/node/v8.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle tedis@0.1.0~preelectron: tedis@0.1.0
6 info lifecycle tedis@0.1.0~electron: tedis@0.1.0
7 verbose lifecycle tedis@0.1.0~electron: unsafe-perm in lifecycle true
8 verbose lifecycle tedis@0.1.0~electron: PATH: /home/kcech/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/opt/tedis/node_modules/.bin:/home/kcech/.nvm/versions/node/v8.2.1/bin:/home/kcech/bin:/home/kcech/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle tedis@0.1.0~electron: CWD: /opt/tedis
10 silly lifecycle tedis@0.1.0~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle tedis@0.1.0~electron: Returned: code: 1  signal: null
12 info lifecycle tedis@0.1.0~electron: Failed to exec electron script
13 verbose stack Error: tedis@0.1.0 electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/kcech/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/kcech/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid tedis@0.1.0
15 verbose cwd /opt/tedis
16 verbose Linux 4.4.0-57-generic
17 verbose argv "/home/kcech/.nvm/versions/node/v8.2.1/bin/node" "/home/kcech/.nvm/versions/node/v8.2.1/bin/npm" "run" "electron"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error tedis@0.1.0 electron: `electron .`
22 error Exit status 1
23 error Failed at the tedis@0.1.0 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
So far, I did not dig deeper.

**Comment by vvondra** [comment]
Just asking the obvious, did you run `npm install`?
